name: usage_stats
description: Query Android Usage Statistics (Configurations, Events, Usage)
version: 0.0.1
homepage: https://github.com/Parassharmaa/usage_stats

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    android:
      package: io.github.parassharmaa.usage_stats
      pluginClass : UsageStatsPlugin
